[2024-06-03T17:38:28.972+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:38:28.988+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:28.995+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:28.996+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:38:29.006+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-11-01 00:00:00+00:00
[2024-06-03T17:38:29.010+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:38:29.012+0000] {standard_task_runner.py:63} INFO - Started process 128 to run task
[2024-06-03T17:38:29.012+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-11-01T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpppytsgf3']
[2024-06-03T17:38:29.013+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask blunders_etl
[2024-06-03T17:38:29.046+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:38:29.105+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-11-01T00:00:00+00:00'
[2024-06-03T17:38:29.106+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:38:29.107+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:38:29.113+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:38:29.118+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:38:29.125+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-11-01T00:00:00+00:00, execution_date=20191101T000000, start_date=20240603T173828, end_date=20240603T173829
[2024-06-03T17:38:29.134+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 27 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 128)
[2024-06-03T17:38:29.145+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:38:29.152+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T17:45:12.774+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:45:12.789+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:12.795+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:12.796+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:45:12.806+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-11-01 00:00:00+00:00
[2024-06-03T17:45:12.811+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:45:12.812+0000] {standard_task_runner.py:63} INFO - Started process 184 to run task
[2024-06-03T17:45:12.813+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-11-01T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp83su_nwz']
[2024-06-03T17:45:12.814+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask blunders_etl
[2024-06-03T17:45:12.846+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T17:45:12.907+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-11-01T00:00:00+00:00'
[2024-06-03T17:45:12.908+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:45:12.909+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:45:12.916+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T17:45:13.884+0000] {logging_mixin.py:188} INFO - No games for period 2019_11
[2024-06-03T17:45:13.884+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T17:45:13.885+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:45:13.891+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-11-01T00:00:00+00:00, execution_date=20191101T000000, start_date=20240603T174512, end_date=20240603T174513
[2024-06-03T17:45:13.909+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T17:45:13.921+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:45:13.923+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:10:40.612+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:10:40.626+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:40.633+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:40.633+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:10:40.643+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-11-01 00:00:00+00:00
[2024-06-08T14:10:40.648+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=191) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:10:40.649+0000] {standard_task_runner.py:63} INFO - Started process 193 to run task
[2024-06-08T14:10:40.650+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-11-01T00:00:00+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp9axl1xwl']
[2024-06-08T14:10:40.650+0000] {standard_task_runner.py:91} INFO - Job 225: Subtask blunders_etl
[2024-06-08T14:10:40.684+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [running]> on host 3c9d89bfdaf1
[2024-06-08T14:10:40.739+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-11-01T00:00:00+00:00'
[2024-06-08T14:10:40.741+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:10:40.741+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:10:40.747+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:10:41.709+0000] {logging_mixin.py:188} INFO - No games for period 2019_11
[2024-06-08T14:10:41.710+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:10:41.710+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:10:41.716+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-11-01T00:00:00+00:00, execution_date=20191101T000000, start_date=20240608T141040, end_date=20240608T141041
[2024-06-08T14:10:41.745+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:10:41.756+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:10:41.758+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:52:07.958+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:52:07.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:07.977+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:07.977+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:52:07.986+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-11-01 00:00:00+00:00
[2024-06-08T14:52:07.992+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=300) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:52:07.994+0000] {standard_task_runner.py:63} INFO - Started process 302 to run task
[2024-06-08T14:52:07.994+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-11-01T00:00:00+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpazbx73fp']
[2024-06-08T14:52:07.995+0000] {standard_task_runner.py:91} INFO - Job 261: Subtask blunders_etl
[2024-06-08T14:52:08.027+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T14:52:08.086+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-11-01T00:00:00+00:00'
[2024-06-08T14:52:08.088+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:52:08.088+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:52:08.095+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:52:08.898+0000] {logging_mixin.py:188} INFO - No games for period 2019_11
[2024-06-08T14:52:08.899+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:52:08.899+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:52:08.906+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-11-01T00:00:00+00:00, execution_date=20191101T000000, start_date=20240608T145207, end_date=20240608T145208
[2024-06-08T14:52:08.930+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:52:08.943+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:52:08.945+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-07T21:20:37.706+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T21:20:37.724+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:37.730+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:37.731+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T21:20:37.741+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-11-01 00:00:00+00:00
[2024-07-07T21:20:37.746+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1365) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T21:20:37.747+0000] {standard_task_runner.py:63} INFO - Started process 1368 to run task
[2024-07-07T21:20:37.748+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-11-01T00:00:00+00:00', '--job-id', '597', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmppd4jst3r']
[2024-07-07T21:20:37.749+0000] {standard_task_runner.py:91} INFO - Job 597: Subtask blunders_etl
[2024-07-07T21:20:37.779+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-11-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T21:20:37.847+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-11-01T00:00:00+00:00'
[2024-07-07T21:20:37.848+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T21:20:37.849+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T21:20:37.854+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T21:20:38.771+0000] {logging_mixin.py:188} INFO - No games for period 2019_11
[2024-07-07T21:20:38.772+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T21:20:38.773+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T21:20:38.778+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-11-01T00:00:00+00:00, execution_date=20191101T000000, start_date=20240707T212037, end_date=20240707T212038
[2024-07-07T21:20:38.803+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T21:20:38.819+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-07T21:20:38.821+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
