[2024-06-03T17:38:28.972+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:38:28.988+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:28.995+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:28.995+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:38:29.006+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-10-01 00:00:00+00:00
[2024-06-03T17:38:29.011+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=125) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:38:29.013+0000] {standard_task_runner.py:63} INFO - Started process 129 to run task
[2024-06-03T17:38:29.013+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-10-01T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpisnlxp94']
[2024-06-03T17:38:29.014+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask blunders_etl
[2024-06-03T17:38:29.046+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:38:29.105+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-10-01T00:00:00+00:00'
[2024-06-03T17:38:29.106+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:38:29.107+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:38:29.113+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:38:29.118+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:38:29.125+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-10-01T00:00:00+00:00, execution_date=20191001T000000, start_date=20240603T173828, end_date=20240603T173829
[2024-06-03T17:38:29.132+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 129)
[2024-06-03T17:38:29.147+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:38:29.153+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T17:45:07.487+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:45:07.502+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:07.509+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:07.509+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:45:07.519+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-10-01 00:00:00+00:00
[2024-06-03T17:45:07.525+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=166) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:45:07.526+0000] {standard_task_runner.py:63} INFO - Started process 168 to run task
[2024-06-03T17:45:07.526+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-10-01T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpj0gpnbb2']
[2024-06-03T17:45:07.528+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask blunders_etl
[2024-06-03T17:45:07.563+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T17:45:07.629+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-10-01T00:00:00+00:00'
[2024-06-03T17:45:07.631+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:45:07.632+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:45:07.640+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T17:45:08.612+0000] {logging_mixin.py:188} INFO - No games for period 2019_10
[2024-06-03T17:45:08.613+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T17:45:08.613+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:45:08.620+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-10-01T00:00:00+00:00, execution_date=20191001T000000, start_date=20240603T174507, end_date=20240603T174508
[2024-06-03T17:45:08.662+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T17:45:08.674+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:45:08.675+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:10:35.705+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:10:35.722+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:35.728+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:35.729+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:10:35.739+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-10-01 00:00:00+00:00
[2024-06-08T14:10:35.745+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=175) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:10:35.746+0000] {standard_task_runner.py:63} INFO - Started process 177 to run task
[2024-06-08T14:10:35.746+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-10-01T00:00:00+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpevmf538b']
[2024-06-08T14:10:35.747+0000] {standard_task_runner.py:91} INFO - Job 223: Subtask blunders_etl
[2024-06-08T14:10:35.784+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [running]> on host 3c9d89bfdaf1
[2024-06-08T14:10:35.851+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-10-01T00:00:00+00:00'
[2024-06-08T14:10:35.852+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:10:35.853+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:10:35.859+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:10:36.865+0000] {logging_mixin.py:188} INFO - No games for period 2019_10
[2024-06-08T14:10:36.866+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:10:36.866+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:10:36.873+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-10-01T00:00:00+00:00, execution_date=20191001T000000, start_date=20240608T141035, end_date=20240608T141036
[2024-06-08T14:10:36.922+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:10:36.934+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:10:36.936+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:52:03.848+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:52:03.866+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:03.873+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:03.873+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:52:03.885+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-10-01 00:00:00+00:00
[2024-06-08T14:52:03.890+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=292) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:52:03.892+0000] {standard_task_runner.py:63} INFO - Started process 294 to run task
[2024-06-08T14:52:03.891+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-10-01T00:00:00+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp0clqrpq1']
[2024-06-08T14:52:03.892+0000] {standard_task_runner.py:91} INFO - Job 259: Subtask blunders_etl
[2024-06-08T14:52:03.924+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T14:52:03.984+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-10-01T00:00:00+00:00'
[2024-06-08T14:52:03.985+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:52:03.986+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:52:03.993+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:52:04.867+0000] {logging_mixin.py:188} INFO - No games for period 2019_10
[2024-06-08T14:52:04.868+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:52:04.869+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:52:04.875+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-10-01T00:00:00+00:00, execution_date=20191001T000000, start_date=20240608T145203, end_date=20240608T145204
[2024-06-08T14:52:04.908+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:52:04.919+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:52:04.920+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-07T21:20:36.021+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T21:20:36.036+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:36.041+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:36.042+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T21:20:36.050+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-10-01 00:00:00+00:00
[2024-07-07T21:20:36.056+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1357) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T21:20:36.057+0000] {standard_task_runner.py:63} INFO - Started process 1361 to run task
[2024-07-07T21:20:36.058+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-10-01T00:00:00+00:00', '--job-id', '595', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpxupb1_3s']
[2024-07-07T21:20:36.058+0000] {standard_task_runner.py:91} INFO - Job 595: Subtask blunders_etl
[2024-07-07T21:20:36.091+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-10-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T21:20:36.149+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-10-01T00:00:00+00:00'
[2024-07-07T21:20:36.150+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T21:20:36.151+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T21:20:36.157+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T21:20:37.078+0000] {logging_mixin.py:188} INFO - No games for period 2019_10
[2024-07-07T21:20:37.078+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T21:20:37.078+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T21:20:37.085+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-10-01T00:00:00+00:00, execution_date=20191001T000000, start_date=20240707T212036, end_date=20240707T212037
[2024-07-07T21:20:37.113+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T21:20:37.129+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-07T21:20:37.131+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
