[2024-06-03T17:38:40.214+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:38:40.229+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:40.235+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:40.236+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:38:40.244+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-02-01 00:00:00+00:00
[2024-06-03T17:38:40.249+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=155) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:38:40.250+0000] {standard_task_runner.py:63} INFO - Started process 160 to run task
[2024-06-03T17:38:40.250+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-02-01T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpwdi59jf_']
[2024-06-03T17:38:40.251+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask blunders_etl
[2024-06-03T17:38:40.283+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:38:40.339+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-02-01T00:00:00+00:00'
[2024-06-03T17:38:40.340+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:38:40.341+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:38:40.346+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:38:40.352+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:38:40.359+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-02-01T00:00:00+00:00, execution_date=20200201T000000, start_date=20240603T173840, end_date=20240603T173840
[2024-06-03T17:38:40.371+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 160)
[2024-06-03T17:38:40.383+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:38:40.393+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:38:40.395+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T17:45:27.547+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:45:27.562+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:27.568+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:27.568+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:45:27.577+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-02-01 00:00:00+00:00
[2024-06-03T17:45:27.582+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=206) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:45:27.583+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-02-01T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp84g3euoo']
[2024-06-03T17:45:27.584+0000] {standard_task_runner.py:63} INFO - Started process 208 to run task
[2024-06-03T17:45:27.584+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask blunders_etl
[2024-06-03T17:45:27.616+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T17:45:27.676+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-02-01T00:00:00+00:00'
[2024-06-03T17:45:27.677+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:45:27.678+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:45:27.684+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T17:45:28.510+0000] {logging_mixin.py:188} INFO - No games for period 2020_02
[2024-06-03T17:45:28.510+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T17:45:28.510+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:45:28.516+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-02-01T00:00:00+00:00, execution_date=20200201T000000, start_date=20240603T174527, end_date=20240603T174528
[2024-06-03T17:45:28.559+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T17:45:28.570+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:45:28.571+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:10:55.881+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:10:55.897+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:55.903+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:55.904+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:10:55.914+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-02-01 00:00:00+00:00
[2024-06-08T14:10:55.920+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=223) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:10:55.922+0000] {standard_task_runner.py:63} INFO - Started process 232 to run task
[2024-06-08T14:10:55.921+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-02-01T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpv111rq1f']
[2024-06-08T14:10:55.922+0000] {standard_task_runner.py:91} INFO - Job 231: Subtask blunders_etl
[2024-06-08T14:10:55.958+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [running]> on host 3c9d89bfdaf1
[2024-06-08T14:10:56.029+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-02-01T00:00:00+00:00'
[2024-06-08T14:10:56.030+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:10:56.031+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:10:56.037+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:10:56.858+0000] {logging_mixin.py:188} INFO - No games for period 2020_02
[2024-06-08T14:10:56.859+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:10:56.859+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:10:56.866+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-02-01T00:00:00+00:00, execution_date=20200201T000000, start_date=20240608T141055, end_date=20240608T141056
[2024-06-08T14:10:56.897+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:10:56.910+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:10:56.911+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:52:24.675+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:52:24.689+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:24.694+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:24.695+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:52:24.704+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-02-01 00:00:00+00:00
[2024-06-08T14:52:24.709+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=332) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:52:24.711+0000] {standard_task_runner.py:63} INFO - Started process 334 to run task
[2024-06-08T14:52:24.711+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-02-01T00:00:00+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp_ihrix1x']
[2024-06-08T14:52:24.712+0000] {standard_task_runner.py:91} INFO - Job 267: Subtask blunders_etl
[2024-06-08T14:52:24.746+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T14:52:24.811+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-02-01T00:00:00+00:00'
[2024-06-08T14:52:24.813+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:52:24.814+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:52:24.820+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:52:25.834+0000] {logging_mixin.py:188} INFO - No games for period 2020_02
[2024-06-08T14:52:25.835+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:52:25.835+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:52:25.842+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-02-01T00:00:00+00:00, execution_date=20200201T000000, start_date=20240608T145224, end_date=20240608T145225
[2024-06-08T14:52:25.887+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:52:25.900+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:52:25.903+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-07T21:20:55.781+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T21:20:55.794+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:55.799+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:55.799+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T21:20:55.806+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-02-01 00:00:00+00:00
[2024-07-07T21:20:55.812+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1429) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T21:20:55.813+0000] {standard_task_runner.py:63} INFO - Started process 1431 to run task
[2024-07-07T21:20:55.813+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-02-01T00:00:00+00:00', '--job-id', '611', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpgdb35b19']
[2024-07-07T21:20:55.814+0000] {standard_task_runner.py:91} INFO - Job 611: Subtask blunders_etl
[2024-07-07T21:20:55.841+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-02-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T21:20:55.901+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-02-01T00:00:00+00:00'
[2024-07-07T21:20:55.902+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T21:20:55.903+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T21:20:55.909+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T21:20:56.882+0000] {logging_mixin.py:188} INFO - No games for period 2020_02
[2024-07-07T21:20:56.883+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T21:20:56.883+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T21:20:56.889+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-02-01T00:00:00+00:00, execution_date=20200201T000000, start_date=20240707T212055, end_date=20240707T212056
[2024-07-07T21:20:56.908+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T21:20:56.926+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-07T21:20:56.927+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
