[2024-06-03T17:38:34.036+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:38:34.053+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:34.061+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:34.061+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:38:34.072+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-12-01 00:00:00+00:00
[2024-06-03T17:38:34.078+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=144) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:38:34.080+0000] {standard_task_runner.py:63} INFO - Started process 147 to run task
[2024-06-03T17:38:34.080+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-12-01T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpexw0wxmt']
[2024-06-03T17:38:34.082+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask blunders_etl
[2024-06-03T17:38:34.121+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:38:34.186+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-12-01T00:00:00+00:00'
[2024-06-03T17:38:34.188+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:38:34.189+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:38:34.194+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:38:34.200+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:38:34.207+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-12-01T00:00:00+00:00, execution_date=20191201T000000, start_date=20240603T173834, end_date=20240603T173834
[2024-06-03T17:38:34.216+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 147)
[2024-06-03T17:38:34.254+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:38:34.265+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:38:34.266+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T17:45:17.487+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:45:17.501+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:17.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:17.507+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:45:17.518+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-12-01 00:00:00+00:00
[2024-06-03T17:45:17.524+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=190) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:45:17.526+0000] {standard_task_runner.py:63} INFO - Started process 192 to run task
[2024-06-03T17:45:17.526+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-12-01T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpjo_zu50s']
[2024-06-03T17:45:17.527+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask blunders_etl
[2024-06-03T17:45:17.560+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T17:45:17.627+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-12-01T00:00:00+00:00'
[2024-06-03T17:45:17.628+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:45:17.629+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:45:17.635+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T17:45:18.556+0000] {logging_mixin.py:188} INFO - No games for period 2019_12
[2024-06-03T17:45:18.557+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T17:45:18.557+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:45:18.564+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-12-01T00:00:00+00:00, execution_date=20191201T000000, start_date=20240603T174517, end_date=20240603T174518
[2024-06-03T17:45:18.581+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T17:45:18.593+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:45:18.594+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:10:45.730+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:10:45.746+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:45.751+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:45.752+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:10:45.762+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-12-01 00:00:00+00:00
[2024-06-08T14:10:45.767+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=199) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:10:45.768+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-12-01T00:00:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpaljnzajf']
[2024-06-08T14:10:45.769+0000] {standard_task_runner.py:63} INFO - Started process 201 to run task
[2024-06-08T14:10:45.769+0000] {standard_task_runner.py:91} INFO - Job 227: Subtask blunders_etl
[2024-06-08T14:10:45.799+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [running]> on host 3c9d89bfdaf1
[2024-06-08T14:10:45.857+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-12-01T00:00:00+00:00'
[2024-06-08T14:10:45.859+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:10:45.860+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:10:45.866+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:10:46.947+0000] {logging_mixin.py:188} INFO - No games for period 2019_12
[2024-06-08T14:10:46.948+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:10:46.948+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:10:46.954+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-12-01T00:00:00+00:00, execution_date=20191201T000000, start_date=20240608T141045, end_date=20240608T141046
[2024-06-08T14:10:46.985+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:10:46.997+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:10:46.999+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:52:13.928+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:52:13.942+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:13.948+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:13.948+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:52:13.958+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-12-01 00:00:00+00:00
[2024-06-08T14:52:13.963+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=316) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:52:13.964+0000] {standard_task_runner.py:63} INFO - Started process 318 to run task
[2024-06-08T14:52:13.965+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-12-01T00:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp20di0s5i']
[2024-06-08T14:52:13.966+0000] {standard_task_runner.py:91} INFO - Job 263: Subtask blunders_etl
[2024-06-08T14:52:13.997+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T14:52:14.054+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-12-01T00:00:00+00:00'
[2024-06-08T14:52:14.055+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:52:14.056+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:52:14.062+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:52:15.057+0000] {logging_mixin.py:188} INFO - No games for period 2019_12
[2024-06-08T14:52:15.058+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:52:15.058+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:52:15.066+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-12-01T00:00:00+00:00, execution_date=20191201T000000, start_date=20240608T145213, end_date=20240608T145215
[2024-06-08T14:52:15.101+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:52:15.115+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:52:15.117+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-07T21:20:46.088+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T21:20:46.101+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:46.106+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:46.106+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T21:20:46.113+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-12-01 00:00:00+00:00
[2024-07-07T21:20:46.119+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1393) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T21:20:46.120+0000] {standard_task_runner.py:63} INFO - Started process 1395 to run task
[2024-07-07T21:20:46.120+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-12-01T00:00:00+00:00', '--job-id', '603', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpy8tg9gye']
[2024-07-07T21:20:46.121+0000] {standard_task_runner.py:91} INFO - Job 603: Subtask blunders_etl
[2024-07-07T21:20:46.149+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-12-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T21:20:46.199+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-12-01T00:00:00+00:00'
[2024-07-07T21:20:46.200+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T21:20:46.201+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T21:20:46.206+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T21:20:47.206+0000] {logging_mixin.py:188} INFO - No games for period 2019_12
[2024-07-07T21:20:47.206+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T21:20:47.207+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T21:20:47.214+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-12-01T00:00:00+00:00, execution_date=20191201T000000, start_date=20240707T212046, end_date=20240707T212047
[2024-07-07T21:20:47.255+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T21:20:47.275+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-07T21:20:47.276+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
