[2024-06-03T17:38:13.126+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:38:13.140+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:13.146+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:13.147+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:38:13.155+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-04-01 00:00:00+00:00
[2024-06-03T17:38:13.160+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:38:13.162+0000] {standard_task_runner.py:63} INFO - Started process 89 to run task
[2024-06-03T17:38:13.161+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpjck_2bw2']
[2024-06-03T17:38:13.162+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask blunders_etl
[2024-06-03T17:38:13.193+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:38:13.251+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-04-01T00:00:00+00:00'
[2024-06-03T17:38:13.253+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:38:13.254+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:38:13.259+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:38:13.265+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:38:13.271+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-04-01T00:00:00+00:00, execution_date=20190401T000000, start_date=20240603T173813, end_date=20240603T173813
[2024-06-03T17:38:13.278+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 89)
[2024-06-03T17:38:13.295+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:38:13.305+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:38:13.307+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T17:44:34.698+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:44:34.714+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2024-06-03T17:44:34.720+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2024-06-03T17:44:34.720+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:44:34.735+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-04-01 00:00:00+00:00
[2024-06-03T17:44:34.740+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:44:34.741+0000] {standard_task_runner.py:63} INFO - Started process 95 to run task
[2024-06-03T17:44:34.742+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpuk_35kxr']
[2024-06-03T17:44:34.743+0000] {standard_task_runner.py:91} INFO - Job 71: Subtask blunders_etl
[2024-06-03T17:44:34.784+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T17:44:34.849+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-04-01T00:00:00+00:00'
[2024-06-03T17:44:34.850+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:44:34.851+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:44:34.858+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T17:44:35.885+0000] {logging_mixin.py:188} INFO - No games for period 2019_04
[2024-06-03T17:44:35.885+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T17:44:35.885+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:44:35.892+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-04-01T00:00:00+00:00, execution_date=20190401T000000, start_date=20240603T174434, end_date=20240603T174435
[2024-06-03T17:44:35.917+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T17:44:35.929+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:44:35.931+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:10:02.444+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:10:02.458+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:02.462+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:02.463+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:10:02.473+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-04-01 00:00:00+00:00
[2024-06-08T14:10:02.478+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=102) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:10:02.479+0000] {standard_task_runner.py:63} INFO - Started process 106 to run task
[2024-06-08T14:10:02.479+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpjzhafvh1']
[2024-06-08T14:10:02.480+0000] {standard_task_runner.py:91} INFO - Job 211: Subtask blunders_etl
[2024-06-08T14:10:02.511+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [running]> on host 3c9d89bfdaf1
[2024-06-08T14:10:02.567+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-04-01T00:00:00+00:00'
[2024-06-08T14:10:02.569+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:10:02.569+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:10:02.577+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:10:03.522+0000] {logging_mixin.py:188} INFO - No games for period 2019_04
[2024-06-08T14:10:03.523+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:10:03.523+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:10:03.530+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-04-01T00:00:00+00:00, execution_date=20190401T000000, start_date=20240608T141002, end_date=20240608T141003
[2024-06-08T14:10:03.575+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:10:03.586+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:10:03.587+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:51:30.308+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:51:30.327+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2024-06-08T14:51:30.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2024-06-08T14:51:30.334+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:51:30.345+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-04-01 00:00:00+00:00
[2024-06-08T14:51:30.351+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=217) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:51:30.352+0000] {standard_task_runner.py:63} INFO - Started process 221 to run task
[2024-06-08T14:51:30.353+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp54wt402x']
[2024-06-08T14:51:30.354+0000] {standard_task_runner.py:91} INFO - Job 247: Subtask blunders_etl
[2024-06-08T14:51:30.386+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T14:51:30.453+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-04-01T00:00:00+00:00'
[2024-06-08T14:51:30.455+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:51:30.456+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:51:30.462+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:51:31.498+0000] {logging_mixin.py:188} INFO - No games for period 2019_04
[2024-06-08T14:51:31.498+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:51:31.499+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:51:31.505+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-04-01T00:00:00+00:00, execution_date=20190401T000000, start_date=20240608T145130, end_date=20240608T145131
[2024-06-08T14:51:31.528+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:51:31.539+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:51:31.541+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-07T21:20:06.084+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T21:20:06.101+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:06.107+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:06.107+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T21:20:06.117+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-04-01 00:00:00+00:00
[2024-07-07T21:20:06.122+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1246) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T21:20:06.123+0000] {standard_task_runner.py:63} INFO - Started process 1250 to run task
[2024-07-07T21:20:06.124+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '573', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp0y9db43_']
[2024-07-07T21:20:06.125+0000] {standard_task_runner.py:91} INFO - Job 573: Subtask blunders_etl
[2024-07-07T21:20:06.156+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-04-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T21:20:06.221+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-04-01T00:00:00+00:00'
[2024-07-07T21:20:06.222+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T21:20:06.223+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T21:20:06.230+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T21:20:07.129+0000] {logging_mixin.py:188} INFO - No games for period 2019_04
[2024-07-07T21:20:07.130+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T21:20:07.130+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T21:20:07.138+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-04-01T00:00:00+00:00, execution_date=20190401T000000, start_date=20240707T212006, end_date=20240707T212007
[2024-07-07T21:20:07.181+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T21:20:07.203+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-07T21:20:07.205+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
