[2024-06-03T17:39:22.897+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:39:22.913+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2024-06-03T17:39:22.918+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2024-06-03T17:39:22.919+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:39:22.929+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-09-01 00:00:00+00:00
[2024-06-03T17:39:22.934+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=225) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:39:22.935+0000] {standard_task_runner.py:63} INFO - Started process 228 to run task
[2024-06-03T17:39:22.937+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-09-01T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp9s2tnt2_']
[2024-06-03T17:39:22.938+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask blunders_etl
[2024-06-03T17:39:22.972+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:39:23.035+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-01T00:00:00+00:00'
[2024-06-03T17:39:23.036+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:39:23.038+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:39:23.044+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:39:23.050+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:39:23.056+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-09-01T00:00:00+00:00, execution_date=20210901T000000, start_date=20240603T173922, end_date=20240603T173923
[2024-06-03T17:39:23.065+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 228)
[2024-06-03T17:39:23.109+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:39:23.121+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:39:23.122+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T22:20:50.167+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T22:20:50.185+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2024-06-03T22:20:50.192+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2024-06-03T22:20:50.193+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T22:20:50.202+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-09-01 00:00:00+00:00
[2024-06-03T22:20:50.210+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=29922) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T22:20:50.211+0000] {standard_task_runner.py:63} INFO - Started process 29924 to run task
[2024-06-03T22:20:50.212+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-09-01T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpwwousok7']
[2024-06-03T22:20:50.213+0000] {standard_task_runner.py:91} INFO - Job 129: Subtask blunders_etl
[2024-06-03T22:20:50.251+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T22:20:50.316+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-01T00:00:00+00:00'
[2024-06-03T22:20:50.317+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T22:20:50.318+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T22:20:50.324+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T22:20:51.232+0000] {logging_mixin.py:188} INFO - No games for period 2021_09
[2024-06-03T22:20:51.233+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T22:20:51.233+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T22:20:51.240+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-09-01T00:00:00+00:00, execution_date=20210901T000000, start_date=20240603T222050, end_date=20240603T222051
[2024-06-03T22:20:51.267+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T22:20:51.282+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T22:20:51.284+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T19:46:40.120+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T19:46:40.134+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2024-06-08T19:46:40.139+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2024-06-08T19:46:40.139+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T19:46:40.148+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-09-01 00:00:00+00:00
[2024-06-08T19:46:40.156+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=30351) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T19:46:40.157+0000] {standard_task_runner.py:63} INFO - Started process 30353 to run task
[2024-06-08T19:46:40.158+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-09-01T00:00:00+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmphnw89qz6']
[2024-06-08T19:46:40.159+0000] {standard_task_runner.py:91} INFO - Job 305: Subtask blunders_etl
[2024-06-08T19:46:40.191+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T19:46:40.253+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-01T00:00:00+00:00'
[2024-06-08T19:46:40.254+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T19:46:40.255+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T19:46:40.261+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T19:46:41.179+0000] {logging_mixin.py:188} INFO - No games for period 2021_09
[2024-06-08T19:46:41.180+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T19:46:41.180+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T19:46:41.187+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-09-01T00:00:00+00:00, execution_date=20210901T000000, start_date=20240608T194640, end_date=20240608T194641
[2024-06-08T19:46:41.213+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T19:46:41.226+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T19:46:41.228+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-08T01:44:45.941+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T01:44:45.954+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2024-07-08T01:44:45.961+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [queued]>
[2024-07-08T01:44:45.961+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-08T01:44:45.970+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-09-01 00:00:00+00:00
[2024-07-08T01:44:45.977+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=31192) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T01:44:45.978+0000] {standard_task_runner.py:63} INFO - Started process 31194 to run task
[2024-07-08T01:44:45.978+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-09-01T00:00:00+00:00', '--job-id', '685', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpujshreji']
[2024-07-08T01:44:45.979+0000] {standard_task_runner.py:91} INFO - Job 685: Subtask blunders_etl
[2024-07-08T01:44:46.016+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-09-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-08T01:44:46.082+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-01T00:00:00+00:00'
[2024-07-08T01:44:46.083+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T01:44:46.084+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-08T01:44:46.091+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-08T01:44:46.999+0000] {logging_mixin.py:188} INFO - No games for period 2021_09
[2024-07-08T01:44:46.999+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-08T01:44:47.000+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T01:44:47.006+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-09-01T00:00:00+00:00, execution_date=20210901T000000, start_date=20240708T014445, end_date=20240708T014447
[2024-07-08T01:44:47.034+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T01:44:47.051+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-08T01:44:47.053+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
