[2024-06-03T17:38:14.994+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:38:15.011+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:15.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:15.020+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:38:15.031+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-05-01 00:00:00+00:00
[2024-06-03T17:38:15.038+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:38:15.039+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-05-01T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp9676yy6i']
[2024-06-03T17:38:15.040+0000] {standard_task_runner.py:63} INFO - Started process 93 to run task
[2024-06-03T17:38:15.040+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask blunders_etl
[2024-06-03T17:38:15.080+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:38:15.153+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-05-01T00:00:00+00:00'
[2024-06-03T17:38:15.154+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:38:15.155+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:38:15.161+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:38:15.168+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:38:15.174+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-05-01T00:00:00+00:00, execution_date=20190501T000000, start_date=20240603T173815, end_date=20240603T173815
[2024-06-03T17:38:15.184+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 93)
[2024-06-03T17:38:15.214+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:38:15.226+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:38:15.227+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T17:44:39.597+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:44:39.613+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2024-06-03T17:44:39.620+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2024-06-03T17:44:39.621+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:44:39.631+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-05-01 00:00:00+00:00
[2024-06-03T17:44:39.637+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=111) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:44:39.638+0000] {standard_task_runner.py:63} INFO - Started process 113 to run task
[2024-06-03T17:44:39.638+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-05-01T00:00:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp0hzvv760']
[2024-06-03T17:44:39.639+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask blunders_etl
[2024-06-03T17:44:39.675+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T17:44:39.739+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-05-01T00:00:00+00:00'
[2024-06-03T17:44:39.740+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:44:39.741+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:44:39.747+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T17:44:40.819+0000] {logging_mixin.py:188} INFO - No games for period 2019_05
[2024-06-03T17:44:40.819+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T17:44:40.820+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:44:40.826+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-05-01T00:00:00+00:00, execution_date=20190501T000000, start_date=20240603T174439, end_date=20240603T174440
[2024-06-03T17:44:40.855+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T17:44:40.867+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:44:40.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:10:08.619+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:10:08.635+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:08.640+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:08.640+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:10:08.650+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-05-01 00:00:00+00:00
[2024-06-08T14:10:08.654+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=120) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:10:08.656+0000] {standard_task_runner.py:63} INFO - Started process 122 to run task
[2024-06-08T14:10:08.656+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-05-01T00:00:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp2cvs4hmv']
[2024-06-08T14:10:08.657+0000] {standard_task_runner.py:91} INFO - Job 213: Subtask blunders_etl
[2024-06-08T14:10:08.692+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [running]> on host 3c9d89bfdaf1
[2024-06-08T14:10:08.752+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-05-01T00:00:00+00:00'
[2024-06-08T14:10:08.753+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:10:08.754+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:10:08.759+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:10:09.702+0000] {logging_mixin.py:188} INFO - No games for period 2019_05
[2024-06-08T14:10:09.703+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:10:09.703+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:10:09.711+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-05-01T00:00:00+00:00, execution_date=20190501T000000, start_date=20240608T141008, end_date=20240608T141009
[2024-06-08T14:10:09.751+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:10:09.762+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:10:09.763+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:51:36.242+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:51:36.259+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2024-06-08T14:51:36.267+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2024-06-08T14:51:36.268+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:51:36.280+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-05-01 00:00:00+00:00
[2024-06-08T14:51:36.286+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=237) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:51:36.287+0000] {standard_task_runner.py:63} INFO - Started process 239 to run task
[2024-06-08T14:51:36.287+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-05-01T00:00:00+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpr8r2tdie']
[2024-06-08T14:51:36.288+0000] {standard_task_runner.py:91} INFO - Job 249: Subtask blunders_etl
[2024-06-08T14:51:36.326+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T14:51:36.389+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-05-01T00:00:00+00:00'
[2024-06-08T14:51:36.391+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:51:36.392+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:51:36.397+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:51:37.334+0000] {logging_mixin.py:188} INFO - No games for period 2019_05
[2024-06-08T14:51:37.335+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:51:37.335+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:51:37.341+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-05-01T00:00:00+00:00, execution_date=20190501T000000, start_date=20240608T145136, end_date=20240608T145137
[2024-06-08T14:51:37.383+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:51:37.394+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:51:37.395+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-07T21:20:06.050+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T21:20:06.065+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:06.072+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:06.073+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T21:20:06.083+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-05-01 00:00:00+00:00
[2024-07-07T21:20:06.089+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1245) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T21:20:06.090+0000] {standard_task_runner.py:63} INFO - Started process 1249 to run task
[2024-07-07T21:20:06.090+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-05-01T00:00:00+00:00', '--job-id', '572', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpovy823de']
[2024-07-07T21:20:06.091+0000] {standard_task_runner.py:91} INFO - Job 572: Subtask blunders_etl
[2024-07-07T21:20:06.126+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-05-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T21:20:06.187+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-05-01T00:00:00+00:00'
[2024-07-07T21:20:06.188+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T21:20:06.189+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T21:20:06.195+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T21:20:07.122+0000] {logging_mixin.py:188} INFO - No games for period 2019_05
[2024-07-07T21:20:07.123+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T21:20:07.123+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T21:20:07.131+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-05-01T00:00:00+00:00, execution_date=20190501T000000, start_date=20240707T212006, end_date=20240707T212007
[2024-07-07T21:20:07.186+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T21:20:07.208+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-07T21:20:07.210+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
