[2024-06-03T17:38:23.320+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:38:23.337+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:23.342+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:23.343+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:38:23.352+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-08-01 00:00:00+00:00
[2024-06-03T17:38:23.358+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=112) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:38:23.359+0000] {standard_task_runner.py:63} INFO - Started process 116 to run task
[2024-06-03T17:38:23.359+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-08-01T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpolcqjqtu']
[2024-06-03T17:38:23.360+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask blunders_etl
[2024-06-03T17:38:23.393+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:38:23.447+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-08-01T00:00:00+00:00'
[2024-06-03T17:38:23.448+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:38:23.449+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:38:23.455+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:38:23.460+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:38:23.466+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-08-01T00:00:00+00:00, execution_date=20190801T000000, start_date=20240603T173823, end_date=20240603T173823
[2024-06-03T17:38:23.474+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 116)
[2024-06-03T17:38:23.493+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:38:23.503+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:38:23.505+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T17:44:57.335+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:44:57.350+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2024-06-03T17:44:57.356+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2024-06-03T17:44:57.356+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:44:57.367+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-08-01 00:00:00+00:00
[2024-06-03T17:44:57.372+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=143) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:44:57.373+0000] {standard_task_runner.py:63} INFO - Started process 145 to run task
[2024-06-03T17:44:57.374+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-08-01T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp5_z4evqf']
[2024-06-03T17:44:57.374+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask blunders_etl
[2024-06-03T17:44:57.405+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T17:44:57.471+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-08-01T00:00:00+00:00'
[2024-06-03T17:44:57.472+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:44:57.473+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:44:57.478+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T17:44:58.370+0000] {logging_mixin.py:188} INFO - No games for period 2019_08
[2024-06-03T17:44:58.371+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T17:44:58.371+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:44:58.378+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-08-01T00:00:00+00:00, execution_date=20190801T000000, start_date=20240603T174457, end_date=20240603T174458
[2024-06-03T17:44:58.429+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T17:44:58.441+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:44:58.443+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:10:25.613+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:10:25.628+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:25.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:25.634+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:10:25.646+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-08-01 00:00:00+00:00
[2024-06-08T14:10:25.652+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=159) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:10:25.653+0000] {standard_task_runner.py:63} INFO - Started process 161 to run task
[2024-06-08T14:10:25.653+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-08-01T00:00:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp0srr2aup']
[2024-06-08T14:10:25.654+0000] {standard_task_runner.py:91} INFO - Job 219: Subtask blunders_etl
[2024-06-08T14:10:25.689+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [running]> on host 3c9d89bfdaf1
[2024-06-08T14:10:25.745+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-08-01T00:00:00+00:00'
[2024-06-08T14:10:25.747+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:10:25.748+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:10:25.753+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:10:26.660+0000] {logging_mixin.py:188} INFO - No games for period 2019_08
[2024-06-08T14:10:26.660+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:10:26.661+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:10:26.672+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-08-01T00:00:00+00:00, execution_date=20190801T000000, start_date=20240608T141025, end_date=20240608T141026
[2024-06-08T14:10:26.709+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:10:26.716+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:51:51.344+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:51:51.358+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2024-06-08T14:51:51.364+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2024-06-08T14:51:51.364+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:51:51.374+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-08-01 00:00:00+00:00
[2024-06-08T14:51:51.379+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=269) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:51:51.380+0000] {standard_task_runner.py:63} INFO - Started process 271 to run task
[2024-06-08T14:51:51.381+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-08-01T00:00:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpytqbrrc4']
[2024-06-08T14:51:51.382+0000] {standard_task_runner.py:91} INFO - Job 255: Subtask blunders_etl
[2024-06-08T14:51:51.415+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T14:51:51.479+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-08-01T00:00:00+00:00'
[2024-06-08T14:51:51.481+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:51:51.481+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:51:51.488+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:51:52.459+0000] {logging_mixin.py:188} INFO - No games for period 2019_08
[2024-06-08T14:51:52.459+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:51:52.460+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:51:52.467+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-08-01T00:00:00+00:00, execution_date=20190801T000000, start_date=20240608T145151, end_date=20240608T145152
[2024-06-08T14:51:52.518+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:51:52.529+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:51:52.530+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-07T21:20:25.739+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T21:20:25.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:25.760+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:25.761+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T21:20:25.769+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-08-01 00:00:00+00:00
[2024-07-07T21:20:25.775+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1317) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T21:20:25.777+0000] {standard_task_runner.py:63} INFO - Started process 1322 to run task
[2024-07-07T21:20:25.777+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-08-01T00:00:00+00:00', '--job-id', '589', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp1pk0cim7']
[2024-07-07T21:20:25.778+0000] {standard_task_runner.py:91} INFO - Job 589: Subtask blunders_etl
[2024-07-07T21:20:25.811+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-08-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T21:20:25.872+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-08-01T00:00:00+00:00'
[2024-07-07T21:20:25.873+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T21:20:25.874+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T21:20:25.881+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T21:20:26.753+0000] {logging_mixin.py:188} INFO - No games for period 2019_08
[2024-07-07T21:20:26.754+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T21:20:26.754+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T21:20:26.761+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-08-01T00:00:00+00:00, execution_date=20190801T000000, start_date=20240707T212025, end_date=20240707T212026
[2024-07-07T21:20:26.793+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T21:20:26.811+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-07T21:20:26.813+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
