[2024-06-03T17:38:40.199+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:38:40.215+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:40.221+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:40.221+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:38:40.231+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-03-01 00:00:00+00:00
[2024-06-03T17:38:40.236+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=156) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:38:40.237+0000] {standard_task_runner.py:63} INFO - Started process 159 to run task
[2024-06-03T17:38:40.237+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-03-01T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmphl9ekt60']
[2024-06-03T17:38:40.238+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask blunders_etl
[2024-06-03T17:38:40.271+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:38:40.326+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-03-01T00:00:00+00:00'
[2024-06-03T17:38:40.327+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:38:40.328+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:38:40.334+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:38:40.340+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:38:40.346+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-03-01T00:00:00+00:00, execution_date=20200301T000000, start_date=20240603T173840, end_date=20240603T173840
[2024-06-03T17:38:40.354+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 159)
[2024-06-03T17:38:40.370+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:38:40.382+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:38:40.384+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T17:45:32.987+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:45:33.003+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:33.011+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:33.011+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:45:33.020+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-03-01 00:00:00+00:00
[2024-06-03T17:45:33.026+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=222) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:45:33.027+0000] {standard_task_runner.py:63} INFO - Started process 224 to run task
[2024-06-03T17:45:33.027+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-03-01T00:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpa1ceziwo']
[2024-06-03T17:45:33.028+0000] {standard_task_runner.py:91} INFO - Job 93: Subtask blunders_etl
[2024-06-03T17:45:33.058+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T17:45:33.119+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-03-01T00:00:00+00:00'
[2024-06-03T17:45:33.120+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:45:33.121+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:45:33.128+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T17:45:34.066+0000] {logging_mixin.py:188} INFO - No games for period 2020_03
[2024-06-03T17:45:34.067+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T17:45:34.067+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:45:34.075+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-03-01T00:00:00+00:00, execution_date=20200301T000000, start_date=20240603T174533, end_date=20240603T174534
[2024-06-03T17:45:34.122+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T17:45:34.135+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:45:34.136+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:11:00.895+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:11:00.908+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [queued]>
[2024-06-08T14:11:00.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [queued]>
[2024-06-08T14:11:00.914+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:11:00.924+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-03-01 00:00:00+00:00
[2024-06-08T14:11:00.929+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:11:00.931+0000] {standard_task_runner.py:63} INFO - Started process 240 to run task
[2024-06-08T14:11:00.931+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-03-01T00:00:00+00:00', '--job-id', '233', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp9b_g9sl2']
[2024-06-08T14:11:00.932+0000] {standard_task_runner.py:91} INFO - Job 233: Subtask blunders_etl
[2024-06-08T14:11:00.964+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [running]> on host 3c9d89bfdaf1
[2024-06-08T14:11:01.021+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-03-01T00:00:00+00:00'
[2024-06-08T14:11:01.023+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:11:01.024+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:11:01.030+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:11:01.880+0000] {logging_mixin.py:188} INFO - No games for period 2020_03
[2024-06-08T14:11:01.881+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:11:01.881+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:11:01.887+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-03-01T00:00:00+00:00, execution_date=20200301T000000, start_date=20240608T141100, end_date=20240608T141101
[2024-06-08T14:11:01.907+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:11:01.918+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:11:01.919+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:52:29.312+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:52:29.327+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:29.332+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:29.332+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:52:29.341+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-03-01 00:00:00+00:00
[2024-06-08T14:52:29.347+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=348) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:52:29.348+0000] {standard_task_runner.py:63} INFO - Started process 350 to run task
[2024-06-08T14:52:29.348+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-03-01T00:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmperaqdjev']
[2024-06-08T14:52:29.349+0000] {standard_task_runner.py:91} INFO - Job 269: Subtask blunders_etl
[2024-06-08T14:52:29.379+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T14:52:29.440+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-03-01T00:00:00+00:00'
[2024-06-08T14:52:29.441+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:52:29.442+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:52:29.448+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:52:30.406+0000] {logging_mixin.py:188} INFO - No games for period 2020_03
[2024-06-08T14:52:30.407+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:52:30.407+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:52:30.414+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-03-01T00:00:00+00:00, execution_date=20200301T000000, start_date=20240608T145229, end_date=20240608T145230
[2024-06-08T14:52:30.444+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:52:30.457+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:52:30.458+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-07T21:20:58.875+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T21:20:58.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:58.893+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:58.893+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T21:20:58.901+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-03-01 00:00:00+00:00
[2024-07-07T21:20:58.907+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1439) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T21:20:58.908+0000] {standard_task_runner.py:63} INFO - Started process 1444 to run task
[2024-07-07T21:20:58.908+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-03-01T00:00:00+00:00', '--job-id', '614', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp8qtu0yid']
[2024-07-07T21:20:58.909+0000] {standard_task_runner.py:91} INFO - Job 614: Subtask blunders_etl
[2024-07-07T21:20:58.943+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-03-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T21:20:59.002+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-03-01T00:00:00+00:00'
[2024-07-07T21:20:59.003+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T21:20:59.003+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T21:20:59.009+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T21:20:59.937+0000] {logging_mixin.py:188} INFO - No games for period 2020_03
[2024-07-07T21:20:59.938+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T21:20:59.938+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T21:20:59.944+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-03-01T00:00:00+00:00, execution_date=20200301T000000, start_date=20240707T212058, end_date=20240707T212059
[2024-07-07T21:20:59.964+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T21:20:59.983+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-07T21:20:59.984+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
