[2024-06-03T17:38:34.036+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:38:34.054+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:34.061+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:34.061+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:38:34.073+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-01-01 00:00:00+00:00
[2024-06-03T17:38:34.078+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=143) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:38:34.080+0000] {standard_task_runner.py:63} INFO - Started process 148 to run task
[2024-06-03T17:38:34.083+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpujb0tkxu']
[2024-06-03T17:38:34.084+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask blunders_etl
[2024-06-03T17:38:34.125+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:38:34.193+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-01-01T00:00:00+00:00'
[2024-06-03T17:38:34.194+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:38:34.195+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:38:34.200+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:38:34.207+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:38:34.212+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-01-01T00:00:00+00:00, execution_date=20200101T000000, start_date=20240603T173834, end_date=20240603T173834
[2024-06-03T17:38:34.223+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 148)
[2024-06-03T17:38:34.255+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:38:34.265+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:38:34.267+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T17:45:22.910+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:45:22.926+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:22.932+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-06-03T17:45:22.933+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:45:22.943+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-01-01 00:00:00+00:00
[2024-06-03T17:45:22.948+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=198) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:45:22.949+0000] {standard_task_runner.py:63} INFO - Started process 200 to run task
[2024-06-03T17:45:22.950+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpe2xv1r_8']
[2024-06-03T17:45:22.951+0000] {standard_task_runner.py:91} INFO - Job 89: Subtask blunders_etl
[2024-06-03T17:45:22.986+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T17:45:23.051+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-01-01T00:00:00+00:00'
[2024-06-03T17:45:23.052+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:45:23.053+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:45:23.060+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T17:45:23.974+0000] {logging_mixin.py:188} INFO - No games for period 2020_01
[2024-06-03T17:45:23.974+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T17:45:23.974+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:45:23.982+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-01-01T00:00:00+00:00, execution_date=20200101T000000, start_date=20240603T174522, end_date=20240603T174523
[2024-06-03T17:45:24.005+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T17:45:24.016+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:45:24.017+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:10:51.865+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:10:51.881+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:51.886+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:51.886+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:10:51.896+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-01-01 00:00:00+00:00
[2024-06-08T14:10:51.901+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:10:51.903+0000] {standard_task_runner.py:63} INFO - Started process 216 to run task
[2024-06-08T14:10:51.903+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpq2jyj5si']
[2024-06-08T14:10:51.903+0000] {standard_task_runner.py:91} INFO - Job 229: Subtask blunders_etl
[2024-06-08T14:10:51.935+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [running]> on host 3c9d89bfdaf1
[2024-06-08T14:10:51.996+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-01-01T00:00:00+00:00'
[2024-06-08T14:10:51.997+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:10:51.998+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:10:52.004+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:10:52.868+0000] {logging_mixin.py:188} INFO - No games for period 2020_01
[2024-06-08T14:10:52.868+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:10:52.869+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:10:52.876+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-01-01T00:00:00+00:00, execution_date=20200101T000000, start_date=20240608T141051, end_date=20240608T141052
[2024-06-08T14:10:52.919+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:10:52.929+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:10:52.931+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:52:19.224+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:52:19.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:19.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-06-08T14:52:19.250+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:52:19.263+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-01-01 00:00:00+00:00
[2024-06-08T14:52:19.270+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=324) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:52:19.271+0000] {standard_task_runner.py:63} INFO - Started process 326 to run task
[2024-06-08T14:52:19.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpl7y0vhzy']
[2024-06-08T14:52:19.272+0000] {standard_task_runner.py:91} INFO - Job 265: Subtask blunders_etl
[2024-06-08T14:52:19.312+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T14:52:19.375+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-01-01T00:00:00+00:00'
[2024-06-08T14:52:19.376+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:52:19.377+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:52:19.384+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:52:20.359+0000] {logging_mixin.py:188} INFO - No games for period 2020_01
[2024-06-08T14:52:20.360+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:52:20.360+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:52:20.367+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-01-01T00:00:00+00:00, execution_date=20200101T000000, start_date=20240608T145219, end_date=20240608T145220
[2024-06-08T14:52:20.407+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:52:20.418+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:52:20.419+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-07T21:20:48.775+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T21:20:48.789+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:48.794+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2024-07-07T21:20:48.795+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T21:20:48.802+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2020-01-01 00:00:00+00:00
[2024-07-07T21:20:48.807+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1403) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T21:20:48.808+0000] {standard_task_runner.py:63} INFO - Started process 1408 to run task
[2024-07-07T21:20:48.809+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '606', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpstwdm4wm']
[2024-07-07T21:20:48.810+0000] {standard_task_runner.py:91} INFO - Job 606: Subtask blunders_etl
[2024-07-07T21:20:48.840+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2020-01-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T21:20:48.899+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2020-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-01-01T00:00:00+00:00'
[2024-07-07T21:20:48.900+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T21:20:48.901+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T21:20:48.908+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T21:20:49.872+0000] {logging_mixin.py:188} INFO - No games for period 2020_01
[2024-07-07T21:20:49.872+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T21:20:49.873+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T21:20:49.879+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2020-01-01T00:00:00+00:00, execution_date=20200101T000000, start_date=20240707T212048, end_date=20240707T212049
[2024-07-07T21:20:49.904+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T21:20:49.922+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-07T21:20:49.923+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
